name: evrakapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  provider: ^6.0.5
  collection: ^1.18.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # EKSİK OLAN VE HATAYA NEDEN OLAN BÖLÜM BUYDU
  # Flutter'a fontların bulunduğu klasörü tanıtıyoruz.
  assets:
    - assets/fonts/

  # Font ailesini ve dosyalarını tanımlıyoruz.
  # Not: 'asset' yolunu tam olarak belirtmek daha sağlıklıdır.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700